### ISSUE TITLE
Use an Adapter in CongratsFragment

### ISSUE THREAD

**Issue by kevinmichaelchen** [Niupiao/niupiao-android#33]
@rynkwn Right now you're using a static class (TempPayInformation) to hold your strings and booleans that will populate EditText and TextView widgets in your UI. You should use an adapter instead. [An adapter is the bridge between the view and the view's underlying data.](http://developer.android.com/reference/android/widget/Adapter.html)

**Comment by rynkwn** [comment]
Will get to this soon

**Comment by kevinmichaelchen** [comment]
See #38. TempPayInformation no longer exists.
