### ISSUE TITLE
Payment Transfer screen

### ISSUE THREAD

**Issue by kevinmichaelchen** [Niupiao/niupiao-android#43]
![1 1payment_transfer](https://cloud.githubusercontent.com/assets/5129994/6586804/04b40b40-c753-11e4-80e9-a2cfec52f3ad.png)

**Comment by rynkwn** [comment]
Layout Drafted

**Comment by kevinmichaelchen** [comment]
@rynkwn So I think the next version of the API gets rid of the hardcoding of events. Specifically, there won't always be two statuses VIP and General with maximum of 2 and 3 purchasable tickets, respectively. Now we have a PaymentManager, so in our TransferTicketsFragment, we can say

``` java
Map<TicketStatus, Collection<Ticket>> tickets = getPaymentManager().getTickets();
Set<TicketStatus> ticketStatuses = tickets.keySet();
for (TicketStatus ticketStatus : ticketStatuses) {
    String name = ticketStatus.getName();    // e.g., "VIP"
    int maxPurchasableTickets = ticketStatus.getMaxPurchasable();    // e.g., 2
    // TODO dynamically add a layout
}
```

In other words, most of the XML will probably have to go.

**Comment by rynkwn** [comment]
@kevinchen93 Sure. I agree, though the visual structure will, in my eyes, remain the same, and the total number of tickets that a particular person can buy will also probably be capped to be about the same. (Perhaps 7-8 all in all). 

The next version of the API should definitely not be hardcoded though. And thanks again for doing so much work Kevin. I hope your stomach flu is getting better!

**Comment by rynkwn** [comment]
@kevinchen93 This may be related to https://github.com/Niupiao/niupiao-android/issues/87 but what I notice is this:

Right now the Map received from paymentManager.getNumTickets() has 0 key-value pairs.
- My apologies. Didn't comment this? I thought I did at 6 this morning.

**Comment by rynkwn** [comment]
MVP version Completed with https://github.com/Niupiao/niupiao-android/pull/96
