### ISSUE TITLE
My Account cannot yet connect to related Fragment Screens

### ISSUE THREAD

**Issue by rynkwn** [Niupiao/niupiao-android#69]
Other fragments are basically connected, as is an AccountActivity, but unsure how to best connect the separate fragments.

**Comment by kevinmichaelchen** [comment]
I'm doing this now

**Comment by kevinmichaelchen** [comment]
Generally, we want to use Activities as sparingly as possible since fragments are faster

**Comment by kevinmichaelchen** [comment]
see #74
