### ISSUE TITLE
EventInfo Needs to be dynamic in order to sync with TransferTickets

### ISSUE THREAD

**Issue by rynkwn** [Niupiao/niupiao-android#80]
@kevinchen93 Right now EventInfo is "General/VIP centric"

I actually believe we should /wait/ until after this week in order to implement more flexible ticket structures.

**Comment by kevinmichaelchen** [comment]
If EventInfo is General/VIP centric, can't we just dynamically build views there?

Are you worried that we won't get dynamic XML in time for the Y-Combinator application?

**Comment by rynkwn** [comment]
Implemented with https://github.com/Niupiao/niupiao-android/pull/94
